---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: "Create file"
    command: "touch /home/ec2-user/test.txt"
  - name: "Store Contents"
    command: echo "Hello" >> /home/ec2-user/test.txt
  - name: "Display content"
    command: cat /home/ec2-user/test.txt
    register: file_content
  - debug:
      msg: "{{ file_content }}"
