---
- hosts: all
  become: yes
  tasks:
    - name: pull from git
      git:
        repo: https://github.com/sivakumarkatam/hello.git
        dest: /var/www/html
        update: yes
        version: master
    - name: "Ensure the service is start"
      service:
        name: httpd
        state: restarted

